---
title: "Varying instruments"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Varying instruments}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
bibliography: ../inst/REFERENCES.bib
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r include = FALSE}
# do.call(knitr::read_chunk, list(path = 'forvignettes/varying_instrument/varying_instrument1.R'))
# do.call(knitr::read_chunk, list(path = 'forvignettes/varying_instrument/plot.R'))
```

## Run simulations
Since this experiment is computationally intensive, it is advisable to run it in parallel. The number of simulations is 100, so one strategy is to run it in chunks of 10 simulations at a time. 

For example, the first chunk of simulation can be run as follows.

```{r setup}
## Non-linear IV estimation.
SIM <- 1:10
```

```{r varying-instrument, echo=TRUE, eval=FALSE}

```


## Plot results
Once the results are saved as `.txt` files, you can produce the plots as follows.

```{r plot-varying-instrument, echo=TRUE, eval=FALSE}

```

